### ISSUE TITLE
Exe doesn't start the server properly

### ISSUE THREAD

**Issue by marcelklehr** [TCB13/LoFloccus#1]
> The current exe doesn't start the server properly

Maybe it's something to do with the windows firewall?

**Comment by TCB13** [comment]
I'm more inclined to think about the exe packing processing because:
1. The server binds to 127.0.0.1 so the firewall shouln't complain about it;
2. It run just fine with `python LoFloccus.py` without any windows firewall popups etc;
3. I've zero experience using `pyinstaller` :P

**Comment by TCB13** [comment]
This is what I did to pack it as an exe:
````
pyinstaller -i icon.ico -F -w .\LoFloccus.py
````
Nothing else at all.

**Comment by marcelklehr** [comment]
I don't think pyinstaller restricts listening on ports.  As the app seems to run fine with pyinstaller and all that's broken is the server, it might be the OS. See https://stackoverflow.com/questions/29373798/socketerror-on-port-80#29378972 for instance. I don't have experience with it either, though. :D

**Comment by TCB13** [comment]
I'm under the impression that I'm failing to bundle some dependency and then the server doesn't work.

**Comment by marcelklehr** [comment]
Is there any way to get debug output?

**Comment by TCB13** [comment]
> Is there any way to get debug output?

I'm investigating this. The `--debug` flag was made for this.

**Comment by TCB13** [comment]
@marcelklehr can you try the zip here https://github.com/TCB13/LoFloccus/releases/tag/1.0.1 ? Thank you.

**Comment by marcelklehr** [comment]
Mh. I currently don't have a windows machine available. It doesn't work out of the box on linux, as I cannot activate the venv that you packaged. (Also, `home = C:\Users\Tadeu Bento\AppData\Local\Programs\Python\Python37-32` is probably not supposed to be in there?)

In order to run it on linux I'd probably need a `requirements.txt` and a python version to set up the virtualenv myself. Are you no longer using pyinstaller?

**Comment by TCB13** [comment]
@marcelklehr I can't get pyinstaller to work under Windows and macOS properly. I was even able to make the app open but then it doesn't start the server.

I decided to pack it individually for each OS. Specifically for Windows I've: created a small C utility that will run `LoFloccus.py` in the included python executable. I've tested on a fresh install of Windows and it works reliably and takes on 4.88MB of space.

**Comment by marcelklehr** [comment]
>  I've: created a small C utility
Ah, ok. :+1:

> But hey, since you're on linux you can simply download LoFloccus.py, and run it in your python. You'll probably need to install some dependencies.

Yeah, a requirements.txt would be nice for that purpose ;)

**Comment by marcelklehr** [comment]
I've updated the floccus README to better integrate LoFloccus in it, btw :)

**Comment by TCB13** [comment]
@marcelklehr I've add a `requirements.txt` file, you may try now!

**Comment by marcelklehr** [comment]
```
Traceback (most recent call last):
  File "./LoFloccus.py", line 191, in <module>
    window.iconbitmap(os.path.join(os.path.dirname(os.path.realpath(__file__)),"icon.ico"))
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/.../LoFloccus/icon.ico" not defined
```

The path is correct, though.

**Comment by TCB13** [comment]
Hmm.. I have no ideia why it is failing in your system... Look here, I just downloaded master as a zip, extracted and run from there...

![image](https://user-images.githubusercontent.com/6315832/55439411-6d636380-559c-11e9-8f76-b958c70f00ae.png)

**Comment by marcelklehr** [comment]
Google gave me this: https://stackoverflow.com/questions/16081201/setting-application-icon-in-my-python-tk-base-application-on-ubuntu

**Comment by TCB13** [comment]
I'm going to close this as the original Windows (exe) issue is fixed. Opened a new issue for the linux icon situation.

**Comment by TCB13** [comment]
@marcelklehr I've just relased v1.1.0 completly rewritten in GoLand with a Qt5 GUI. That should be much more pleasant to run under macOS / Linux. I'll release soon compiled binaries for those.
