### ISSUE TITLE
XBEL consult 

### ISSUE THREAD

**Issue by Ynjxsjmh** [TCB13/LoFloccus#10]
OS: win 7 
ff version 68.7.0esr (64-bit)
Google Chrome version 80.0

I didn't find options about Firefox and Google Chrome exporting bookmarks as xbel but html. What way do you recommend to get that kind of file?

**Comment by TCB13** [comment]
Hello,

I beleive you're missing the point of this tool and Floccus, please read the documentation here https://github.com/marcelklehr/floccus and here https://github.com/TCB13/LoFloccus .

**Comment by Ynjxsjmh** [comment]
Thanks for your reply, I misunderstood how it works before. I thought I need to export my bookmarks data manually and use that data in different browsers but it turns out *.xbel is automatically created by the extension. Now it works fine, looks awesome.

**Comment by TCB13** [comment]
@Ynjxsjmh I'm happy you sorted out the situation 👍
