### ISSUE TITLE
add compile instruction for linux to readme

### ISSUE THREAD

**Issue by freddii** [TCB13/LoFloccus#11]
in this issue: https://github.com/TCB13/LoFloccus/issues/7#issuecomment-559799386 
it is mentioned that it is possible to compile it for linux.
Sadly there is no exactly instruction how to compile it for linux.
Is it possible to get an instruction?

**Comment by freddii** [comment]
As mentioned in:https://github.com/TCB13/LoFloccus/issues/4#issuecomment-559149219

at the moment it is less hassle to simply run:
pip3 install WsgiDAV
pip3 install gevent
wsgidav -r /path/to/bookmarks/folder -p 8008 --auth anonymous --server gevent

flocus setup:
http://localhost:8008/
anonymous

**Comment by test-0-zero** [comment]
>     4. `cd LoFloccus`
> 
>     5. `qtdeploy build desktop .`
> 
when i compile i get this error message:

$ /home/riccardo/go/bin/qtdeploy build desktop .
ERRO[0059] failed to run command                         _func=RunCmd cmd="go build -p 8 -v -ldflags=all=\"-s\" \"-w\" -trimpath -o /home/riccardo/LoFloccus-master/deploy/linux/LoFloccus-master -tags=minimal" dir=/home/riccardo/LoFloccus-master env="GDMSESSION=mate GOROOT=/usr/local/go GTK_MODULES=appmenu-gtk-module:gail:atk-bridge:canberra-gtk-module XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/riccardo DESKTOP_SESSION=mate LANG=it_IT.UTF-8 USER=riccardo MATE_DESKTOP_SESSION_ID=this-is-deprecated XAUTHORITY=/home/riccardo/.Xauthority XDG_SESSION_ID=c10 XDG_RUNTIME_DIR=/run/user/1000 COMPIZ_CONFIG_PROFILE=mate SESSION_MANAGER=local/SSDUB18:@/tmp/.ICE-unix/197793,unix/SSDUB18:/tmp/.ICE-unix/197793 SSH_AUTH_SOCK=/run/user/1000/keyring/ssh LESSCLOSE=/usr/bin/lesspipe %s %s GTK_OVERLAY_SCROLLING=0 QT_DIR=/home/riccardo/go/src/github.com/therecipe/env_linux_amd64_513 XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1 LANGUAGE=it_IT GDM_LANG=it_IT VTE_VERSION=6003 XDG_SESSION_CLASS=user XDG_VTNR=7 CGO_ENABLED=1 GOPATH=/home/riccardo/go GOARCH=amd64 XDG_SEAT=seat0 GOOS=linux CGO_LDFLAGS=-Wl,-rpath,$ORIGIN/lib -Wl,--disable-new-dtags HOME=/home/riccardo QT_SCALE_FACTOR=1 _=/home/riccardo/go/bin/qtdeploy SSH_AGENT_PID=197878 XDG_SESSION_DESKTOP=mate GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1 XDG_CURRENT_DESKTOP=MATE UBUNTU_MENUPROXY=1 SHELL=/bin/bash COLORTERM=truecolor TERM=xterm-256color SHLVL=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36: XDG_DATA_DIRS=/usr/share/mate:/usr/local/share:/usr/share:/var/lib/snapd/desktop OLDPWD=/home/riccardo QT_ACCESSIBILITY=1 PWD=/home/riccardo/LoFloccus-master QT_QPA_PLATFORMTHEME=gtk2 XDG_SESSION_TYPE=x11 PATH=/home/riccardo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin LOGNAME=riccardo WINDOWID=56623110 XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0 DISPLAY=:0 LESSOPEN=| /usr/bin/lesspipe %s DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus GO111MODULE=off" error="exit status 2" name="build for linux on linux"
github.com/therecipe/qt/core
github.com/therecipe/qt/gui
github.com/therecipe/qt/widgets
github.com/therecipe/qt/uitools
_/home/riccardo/LoFloccus-master
# _/home/riccardo/LoFloccus-master
./LoFloccus.go:107:30: too many arguments in call to gui.NewQPixmap5
	have (string, string, core.Qt__ImageConversionFlag)
	want (gui.QPixmap_ITF)

can you hemp me ? please.

**Comment by TCB13** [comment]
This issue is not invalid since the project was rewritten from the scratch.
