### ISSUE TITLE
[Security] Recommend in the settings to set encryption password in floccus !

### ISSUE THREAD

**Issue by BirdInFire** [TCB13/LoFloccus#15]
Like the title say i think it must be heavylly recommended to user to actually encrypt their bookmark in floccus.

Because technically since http in loop is used and the config settings is readable a malware can easilly modify the xbel file if not encrypted (who can potentially redirect user of all the synced computer to visit malware website instead of their bookmarked one).

NOTE : For those who will say a malware will directly modify the XBEL don't forged the antiransomware of windows will lock him from modify it directly where (if i use lofloccus) high is the possibility that lofloccus is whitelisted.

**Comment by TCB13** [comment]
You have a valid point. Will be added to the backlog. Thank you.

**Comment by TCB13** [comment]
Issue closed with the release of version 1.2.3. https://github.com/TCB13/LoFloccus/releases/tag/1.2.3
