### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [TCB13/LoFloccus#16]
i've downloaded version 1.2.2 but the version numbers are missing. all macOS apps are supposed to have version numbers. both the CFBundleVersion and the CFBundleShortVersionString entries are missing from your Info.plist file.

this is a regression. at least version 1.1.2 did contain proper version numbers (and a copyright notice). 

<img width="260" alt="Screenshot 2022-03-31 at 18 10 44" src="https://user-images.githubusercontent.com/1261954/161101057-b2acbb4b-f9da-43ca-a46c-a2b4389b84ec.png">

**Comment by TCB13** [comment]
Hello. 

This is indeed a regression caused by the complete rewrite of the application that took place in v1.2 and 1.2.1 that made the App way better for macOS. https://github.com/TCB13/LoFloccus/tree/1.2.1

Thank you for noticing this. I'll have a look at it.

**Comment by TCB13** [comment]
Issue closed with the release of version 1.2.3. https://github.com/TCB13/LoFloccus/releases/tag/1.2.3

**Comment by core-code** [comment]
confirmed fixed, thanks for the quick turnaround!
