### ISSUE TITLE
Request for new feature allowing Html file sync.

### ISSUE THREAD

**Issue by Virgus** [TCB13/LoFloccus#17]
Hello, a few days ago the latest floccus version was released. It has the html sync option enabled to allow compatibility with older browsers.

It would be great to have an updated Lofloccus version, able to sync to local html files too, so to extend its possibilities.

Thanks.

**Comment by TCB13** [comment]
Hi @Virgus thank you for the heads up. It seems the feature still has a few bugs (https://github.com/floccusaddon/floccus/issues/1232) but I'll review it and update LoFloccus as soon as I can.

**Comment by Virgus** [comment]
Great, thanks ! I didn't have the time to test it yet but I'm looking forward to using this feature soon...
Have a nice day,
V.

**Comment by TCB13** [comment]
@Virgus its done, check https://github.com/TCB13/LoFloccus/releases/tag/1.2.4

**Comment by Virgus** [comment]
Great news ! Thank you so much. I'll download now and test tomorrow.
Cheers,
V.
