### ISSUE TITLE
Linux installation instructions?

### ISSUE THREAD

**Issue by sunjam** [TCB13/LoFloccus#5]
Hi, I was looking for Linux installation instructions.  I see [mention](https://github.com/TCB13/LoFloccus/issues/4) of others using this on [Kubuntu](https://github.com/TCB13/LoFloccus/issues/2) successfully.

**Comment by marlluslustosa** [comment]
I launched a webdav server for GNU/Linux for the browser Floccus plugin.

https://github.com/marlluslustosa/LoFloccus-Docker

**Comment by TCB13** [comment]
@marlluslustosa nice one!
