### ISSUE TITLE
Tags / Category Support?

### ISSUE THREAD

**Issue by noskule** [TCB13/LoFloccus#6]
Hi, I did try out this plugin with firefrox / nextcloud 16.04. The sync went fine but without the tags. Are tags supported?

**Comment by marcelklehr** [comment]
Browsers don't support tags at the moment, sadly. Mozilla might support this at some point, but they're holding off exposing their tags to extensions until they've overhauled their bookmarks code. :man_shrugging:

**Comment by TCB13** [comment]
@noskule as @marcelklehr already said this is a browser related issue. Anyway I'm closing this issue because it's not related to LoFloccus and seems to be answered. Thank you all!
