### ISSUE TITLE
Feature Request; Start directly to tray (Windows)

### ISSUE THREAD

**Issue by r4taw2mg** [TCB13/LoFloccus#8]
Hi, 

thank you for this nice, little program, which is very useful to me. There is one small thing, though, that would make it perfect for me.

Could you please add a option to the command line, to start the application directly to the tray (i.e. with no dialogue showing up)?

Thank you.

**Comment by TCB13** [comment]
Hi, if you check both of the checkboxes it will start directly to the tray:
![image](https://user-images.githubusercontent.com/6315832/70226022-02c88000-1748-11ea-8861-b971e960d700.png)
